#!/bin/bash
#
# Runs all tests & lint.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

header "Tests"
go test -v $(glide novendor)

header "Linter"
gometalinter --deadline=1m --vendored-linters --vendor --disable=gotype

header "Flint"
flint --skip-changelog --skip-code-of-conduct
# vim: set ft=sh :